### ISSUE TITLE
Support for XXH3_128bits?

### ISSUE THREAD

**Issue by firasuke** [OpenSystemsLab/xxhash.nim#4]
Hey there,

Are you planning on adding support for `XXH3_128bits` (similar to what `xxh128sum` does)?

**Comment by firasuke** [comment]
Here is what I am trying to build:

```Nim
import xxhash

proc verify*(file: string, checksum: string): bool =
    checksum == xxhash3_128(readFile(file))
```

Where file is a .tar.gz tarball (I'll be using [`make-4.4.tar.gz`](https://ftpmirror.gnu.org/make/make-4.4.tar.gz) as an example.

I am using xxh128sum to get the expected checksum `15bf27bd70e74eb8c4f71a1028513adf`.

Is this doable?

**Comment by ba0f3** [comment]
XXH128 added in release v0.11.0

**Comment by firasuke** [comment]
> XXH128 added in release v0.11.0

Thanks! I tried to use it with `readFile`:

```Nim
echo XXH3_128bits(readFile("someFile"))
```

I am getting the following as output:

```
(lo: 16398121194546955978, hi: 2346399041289641478)
```

**Comment by firasuke** [comment]
Ok so I imported `nint128` and it worked just fine.

Thanks again for your work on this, much appreciated!
